// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDryGSDbxwqhxsnEsfGFVvjyYnkr-RGVJM',
    appId: '1:661262855692:web:08e25f267926b4a3dac829',
    messagingSenderId: '661262855692',
    projectId: 'finmate-project',
    authDomain: 'finmate-project.firebaseapp.com',
    storageBucket: 'finmate-project.firebasestorage.app',
    measurementId: 'G-F0QY8W7JFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMYoYxGbFibCgB9IDH7A93cEqtvHZgklE',
    appId: '1:661262855692:android:4da34c250ad26934dac829',
    messagingSenderId: '661262855692',
    projectId: 'finmate-project',
    storageBucket: 'finmate-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj2WV2NLc1dd8dEira1AhuN0Z78E2lKqU',
    appId: '1:661262855692:ios:21a67ddd1d3c01fedac829',
    messagingSenderId: '661262855692',
    projectId: 'finmate-project',
    storageBucket: 'finmate-project.firebasestorage.app',
    androidClientId: '661262855692-j7bqo75k04j5v9cncost865h3i4npkud.apps.googleusercontent.com',
    iosClientId: '661262855692-6jse3e4q35b8j59v795se1hphlk5evmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.finmate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj2WV2NLc1dd8dEira1AhuN0Z78E2lKqU',
    appId: '1:661262855692:ios:21a67ddd1d3c01fedac829',
    messagingSenderId: '661262855692',
    projectId: 'finmate-project',
    storageBucket: 'finmate-project.firebasestorage.app',
    androidClientId: '661262855692-j7bqo75k04j5v9cncost865h3i4npkud.apps.googleusercontent.com',
    iosClientId: '661262855692-6jse3e4q35b8j59v795se1hphlk5evmb.apps.googleusercontent.com',
    iosBundleId: 'com.example.finmate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDryGSDbxwqhxsnEsfGFVvjyYnkr-RGVJM',
    appId: '1:661262855692:web:04a819b67b46ef1adac829',
    messagingSenderId: '661262855692',
    projectId: 'finmate-project',
    authDomain: 'finmate-project.firebaseapp.com',
    storageBucket: 'finmate-project.firebasestorage.app',
    measurementId: 'G-MWJSS3XPPC',
  );

}